version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgpassword
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5450:5432

  redis:
    image: redis:5.0.5-alpine
    volumes:
      - ./volumes/redis:/usr/local/etc/redis
    ports:
      - 6380:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    environment:
      - spring.profiles.active=test
    ports:
      - "8200:8100"
    depends_on:
      - postgres
      - redis
