version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgpassword
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5450:5432
